version: '3.3'

services:
   db:
     restart: always
     image: mysql:5.7
     volumes:
     - ./db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: quest
       MYSQL_DATABASE: quest
       MYSQL_USER: quest
       MYSQL_PASSWORD: quest

   phpmyadmin:
     restart: always
     image: phpmyadmin/phpmyadmin:4.6
     container_name: phpmyadmin
     links:
       - db:db
     ports:
      - 8001:80
     environment:
       MYSQL_USER: quest
       MYSQL_PASSWORD: quest
       MYSQL_ROOT_PASSWORD: quest

   go:
     restart: always
     image: iron/go
     working_dir: /run
     volumes:
       - .:/run
     ports:
       - 8080:8080
     depends_on:
       - db
     environment:
       appPort: :8080
       dbHost: db
       dbName: quest
       dbUser: quest
       dbPswd: quest
     command: ["/run/questionnaire"]

   swagger:
     restart: always
     image: swaggerapi/swagger-ui:3.18.1
     container_name: swagger-ui
     environment:
        API_URL: http://localhost:8080/static/swagger.json
     ports:
      - 8002:8080

volumes:
    db_data:
