version: '3.3'

services:
   db:
     restart: always
     image: mysql:5.7
     volumes:
     - ./test_db_data:/var/lib/mysql
     ports:
      - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: quest_test
       MYSQL_DATABASE: quest_test
       MYSQL_USER: quest_test
       MYSQL_PASSWORD: quest_test

volumes:
    test_db_data:
